---
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"

- name: Distribution version lower
  debug: msg="{{ ansible_distribution|lower}}"

## Install Docker packages
- name: Install apt-transport-https package
  apt:
    name: apt-transport-https
    install_recommends: no
    state: latest
  when: ansible_os_family == "Debian"

# TODO-PI update for getting proper packages for Raspbian - add packages libffi-dev libssl-dev
- name: Add Docker GPG key to APT
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
  when:  ansible_os_family == "Debian"

